### ISSUE TITLE
initilization of no init variable

### ISSUE THREAD

**Issue by Bergi84** [nvitya/vihal#12]
in file \vihal\armm\RP\src\clockcnt_rp.cpp there are following lines of code:

__attribute__((section(".noinit")))
uint32_t  rp_watchdog_tick_mul = 1;

which leads to a compiler error during build:
/vihal/armm/RP/src/clockcnt_rp.cpp:33:11: error: only zero initializers are allowed in section '.noinit'

**Comment by nvitya** [comment]
Thank you for pointing out, fix just committed.
